### PR TITLE
Less repetition in the code

### PR DESCRIPTION
**Pull request by tech6hutch**
### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]
Patch ¯\\\_(ツ)\_/¯
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- DRY

### (If Applicable) What Issue does it fix?
"Fixes" repetition, if anything.

### CODE REVIEW

**Comment by UnseenFaith** [comment]
I suggest moving this outside of the constructor, otherwise it'll have to create that object every single time, as opposed to once when the file is loaded.
Edit: Yes it's only loaded once anyway, but I think it's probably better practice to leave it out of the constructor.

**Comment by CyberiumShadow** [comment]
Already changed on my end, will push to it soon

**Comment by CyberiumShadow** [comment]
@UnseenFaith Requested Changes submitted. Acceptable?

**Comment by kyranet** [comment]
@CyberiumShadow I think he meant outside the class. Also, you can't reference a non-static method like `makeDirsObject` with the class name, it must be with the keyword `this`

**Review by UnseenFaith — DISMISSED** [review]
Move it completely outside of the the class. It doesn't need to be a method on the class, just needs to be an object you can access one time and then never use again.
```js
const makeDirObjects = (dir) => ({...}):
```

**Comment by bdistin** [comment]
In that case shouldn't it instead be defined in the constructor, so that it can be garbage collected, instead of perpetually stored in the process cache?

**Comment by UnseenFaith** [comment]
Is that how it works? I thought it worked the complete opposite. If that's the case then yes it should stay in the constructor.

**Comment by CyberiumShadow** [comment]
okay now @UnseenFaith @bdistin ?

**Review by bdistin — APPROVED** [review]
LGTM

**Pull request merged**
