### PR TITLE
Update eval.js

### PR DESCRIPTION
**Pull request by Stitch07**
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Send evaled output as an attachment if it's too big
-
-

### (If Applicable) What Issue does it fix?

 Fixes... 

Eval silently erring if output is greater than 1992 characters

### CODE REVIEW

**Comment by tech6hutch** [comment]
My [PR](https://github.com/dirigeants/komada/pull/368) also has / will have this fix. That's...maybe a little while before that's done, though. This is a good change in the meantime.

**Comment by CyberiumShadow** [comment]
Is there any benefits in directly sending the attachment vs uploading the eval to a hastebin for example and then providing the haste link?

**Comment by kyranet** [comment]
Yes, you can send 8 MB worth of chars.

**Comment by CyberiumShadow** [comment]
Unless you're nitro. then you can send 50mb worth of chars 🥇

**Comment by Stitch07** [comment]
So anyway...

**Review by CyberiumShadow — APPROVED** [review]
Looks good

**Pull request merged**
