### PR TITLE
Use fetch method from stores

### PR DESCRIPTION
**Pull request by Pandraghon**
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

-
-
-

### (If Applicable) What Issue does it fix?

channel.fetchMessage, client.fetchUser, guild.fetchMember are no longer available => replaced in Resolver by [store].fetch

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
This isn't really needed atm since package-locks lock us in to a commit prior to this breaking change.
Will leave this open though

**Comment by Pandraghon** [comment]
It seems to be already usable :

**Comment by kyranet** [comment]
Komada is using a different Discord.JS version than yours, that's why.

**Comment by Pandraghon** [comment]
But I do not use Discord.JS directly anymore, only through Komada. It is not in my package.json.

**Comment by CyberiumShadow** [comment]
Can you give us the package-lock **hash** for Discord.JS

**Comment by Pandraghon** [comment]
```json
{
  "dependencies": {
    "discord.js": {
      "version": "https://registry.npmjs.org/discord.js/-/discord.js-11.1.0.tgz",
      "integrity": "sha1-U1HVnjeY9TbeGXXpLK5NEa89kmY=",
      "requires": {
        "long": "https://registry.npmjs.org/long/-/long-3.2.0.tgz",
        "prism-media": "https://registry.npmjs.org/prism-media/-/prism-media-0.0.1.tgz",
        "snekfetch": "https://registry.npmjs.org/snekfetch/-/snekfetch-3.1.7.tgz",
        "tweetnacl": "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz",
        "ws": "https://registry.npmjs.org/ws/-/ws-2.3.1.tgz"
      }
    },
    "komada": {
      "version": "github:dirigeants/komada#2c3d69870f780b714ee929a7fe836c006d7c877f",
      "requires": {
        "chalk": "2.1.0",
        "discord.js": "github:hydrabolt/discord.js#3c532f16bc48175597a7bbed4fbba4637812184d",
        "fs-nextra": "0.2.0",
        "moment": "2.18.1",
        "moment-duration-format": "1.3.0",
        "performance-now": "2.1.0"
      },
      "dependencies": {
        "discord.js": {
          "version": "github:hydrabolt/discord.js#3c532f16bc48175597a7bbed4fbba4637812184d",
          "requires": {
            "long": "3.2.0",
            "prism-media": "0.0.1",
            "snekfetch": "3.2.9",
            "tweetnacl": "1.0.0",
            "ws": "3.1.0"
          }
        }
      }
    }
  }
}
```
It looks like I forgot to `npm prune`. 
But my version was based on NPM package, not master branch.

**Comment by CyberiumShadow** [comment]
NPM Komada shouldn't even be this far into d.js

You also have d.js 11.1
And the underlying d.js within your Komada install does not match the package-lock in the repository
In fact, it's at least 10 commits ahead,

**Comment by Pandraghon** [comment]
I meant my *d.js* version was from NPM

**Comment by CyberiumShadow** [comment]
Regardless, you have two version of d.js installed.

For the purpose of debugging, I want you to ensure ur package.json only has Komada in it.

And I want you to delete node_modules and package-lock.json

Run `npm install` and test the fetchMessage and messages.fetch for me.

**Comment by Pandraghon** [comment]
Removed node_modules and package-lock.json. Only komada in package.json :

**package.json**
```json
{
   ...
  "dependencies": {
    "discord-emoji": "^1.1.1",
    "komada": "github:dirigeants/komada#master",
    "moment": "^2.18.1",
    "moment-duration-format": "^1.3.0",
    "ytdl-core": "^0.17.0"
  },
}
```
The other dependencies were installed by komada on the first run

**package-lock.json**
```json
{
  "dependencies": {
    "komada": {
      "version": "github:dirigeants/komada#2c3d69870f780b714ee929a7fe836c006d7c877f",
      "requires": {
        "chalk": "2.1.0",
        "discord.js": "github:hydrabolt/discord.js#b7c55f02c20bee5dab107ff453a6d3ea1a4a776a",
        "fs-nextra": "0.2.0",
        "moment": "2.18.1",
        "moment-duration-format": "1.3.0",
        "performance-now": "2.1.0"
      },
      "dependencies": {
        "discord.js": {
          "version": "github:hydrabolt/discord.js#b7c55f02c20bee5dab107ff453a6d3ea1a4a776a",
          "requires": {
            "long": "3.2.0",
            "prism-media": "0.0.1",
            "snekfetch": "3.2.9",
            "tweetnacl": "1.0.0",
            "ws": "3.1.0"
          }
        }
      }
    }
  }
}
```

**Comment by CyberiumShadow** [comment]
hmm, I have no idea why, but it's completely ignoring komada's package-locks.

What version of npm

**Comment by Pandraghon** [comment]
```bash
$ npm -v                                                                                                  
5.3.0                                                                                                                                   
$ node -v                                                                                                 
v8.3.0 
```

**Comment by CyberiumShadow** [comment]
NPM seems to be ignoring the package-locks. 

Going to manually merge this with a updated package-lock.

Komada will increase to 0.20.8

**Pull request closed without merging**
