### PR TITLE
SettingsCache Addition

### PR DESCRIPTION
**Pull request by UnseenFaith**
### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]
Patch
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Creates a more user-friendly way of adding your own Settings to Komada.

### CODE REVIEW

**Comment by kyranet** [comment]
Alright, I fixed a bunch of bugs, right now I can list two things in the to-do:

- [x] Fix the function validator for `client.settings.add`, Function has a prototype, AsyncFunction doesn't.
- [ ] Detect gateways created previously, instead of having a function with init and add it once and again.

**Comment by tech6hutch** [comment]
Wow, you're right; async functions don't have a prototype. That's so screwy.

**Review by kyranet — DISMISSED** [review]
Tested, seems to be working now.

**Review by kyranet — DISMISSED** [review]
Everything looks fine to me now.

**Review by kyranet — DISMISSED** [review]
Now, I'm gonna merge this.

**Review by kyranet — APPROVED** [review]

**Pull request merged**
