### PR TITLE
Create CommandMessage instead of Messages

### PR DESCRIPTION
**Pull request by UnseenFaith**
### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]
Minor
I don't think there is any breaking changes in this, but due to the nature of this PR we should increment one minor.
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Refactored CommandMessage to extend Message instead.
- Create CommandMessages from Komada instead of Messages from Discord.js.
- All messages are now instances of CommandMessage, and the respected command values, prefix, command, prefixLength, will be null if they don't exist.

This PR is no where near finished, and not everything in implemented/changed/fixed yet. The only thing guaranteed to be working is commands, and command logging. The message event will need a full refactor, along with any other places where we may use 'cmdMsg'

Additionally, all other places in Discord.js that return `new Message()` will need to be changed to `new CommandMessage()` instead. (for ex: fetchMessage)

The other alternative to this is to take it a step backwards, and only create CommandMessages when Komada considers them to be a commandMessage, and then emit a commandMessage event.

### CODE REVIEW

**Comment by tech6hutch** [comment]
Wouldn't incrementing major mean 1.0.0 release?

**Comment by UnseenFaith** [comment]
Uh yeah you're right, lemme fix that.

**Comment by CyberiumShadow** [comment]
major lol

**Comment by UnseenFaith** [comment]
Actions are being removed in v12

**Pull request closed without merging**
