### PR TITLE
Monitors addition

### PR DESCRIPTION
**Pull request by UnseenFaith**
The Hall Monitors have arrived. :smile:
Adds:

- loadCommandMonitors (loads monitors)
- runCommandMonitors (runs monitors if they're enabled)
- profanity.js (First Monitor, disabled by default to prevent issues)

Modifies:
- App.js (Now Runs monitors before the checking of the command && ignores its own messages to prevent an infinite loop... might be useful if we prevent all bots messages.. //givemesuggestions)

### CODE REVIEW

**Comment by UnseenFaith** [comment]
@CyberiumShadow Not an error/issue or anything but just wanted to say I left
`console.log(reason.stack);` in there by mistake. This is the thing you said we might want to consider adding into core komada for errors. Your call if you want to leave it in or not.

**Comment by CyberiumShadow** [comment]
@UnseenFaith Ignoring bot messages can be done by checking if message author is a bot
`if (msg.author.bot) {return;}`

**Comment by CyberiumShadow** [comment]
[Implement "Monitors"](https://trello.com/c/1d1dro2Y/5-implement-monitors)

**Comment by CyberiumShadow** [comment]
[Individual reload for functions, inhibitors, dataProviders](https://trello.com/c/t2CiCV7e/10-individual-reload-for-functions-inhibitors-dataproviders)

**Pull request merged**
