### PR TITLE
Typing

### PR DESCRIPTION
**Pull request by Stitch07**
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Adds a client option: typing

### (If Applicable) What Issue does it fix?

Not a fix.

 Wrote it in a hurry but worked on my bot. :+1:

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
@kyranet @UnseenFaith

**Comment by CyberiumShadow** [comment]
anything gonna happen?

**Comment by kyranet** [comment]
This is a direct port of Klasa's typing, but it got improved and this PR didn't get updated (yet).

**Comment by UnseenFaith** [comment]
Closing this PR due to the fact that it's been almost two months with no updates, and I'm currently rewriting Komada. If you'd like to reopen this feel free too.

**Pull request closed without merging**
