### PR TITLE
Update parsedUsage.js

### PR DESCRIPTION
**Pull request by kyranet**
### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]
N/a
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Performance.

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
is this complete/are we still following this?

**Comment by kyranet** [comment]
Ao was supposed to review this... but he didn't

**Comment by kyranet** [comment]
This PR will be pending until we decide to merge it for #323

**Comment by CyberiumShadow** [comment]
Now obsolete

**Pull request closed without merging**
