### PR TITLE
Added padding to help command

### PR DESCRIPTION
**Pull request by novara754**

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
Indev branch pls

**Comment by ghost** [comment]
@vzwGrey yea could you change to indev and also try using this [padding](https://github.com/eslachance/komada-pieces/pull/11)

**Comment by eslachance** [comment]
@vzwGrey you need to edit this so it doesn't use an external pad function, remember? I can't accept this in the current state.

**Comment by eslachance** [comment]
Apologies @vzwGrey , really really sorry, I had to revert to the previous help command because mine had... uhm... "problems". I would be very grateful if you could pull the current code and go from there.

**Pull request closed without merging**
